/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Admin_Space_V2 (void)
{
  GtkWidget *Admin_Space_V2;
  GtkWidget *notebook1;
  GtkWidget *notebook4;
  GtkWidget *hbox60;
  GtkWidget *fixed35;
  GtkWidget *names1;
  GtkObject *durations1_adj;
  GtkWidget *durations1;
  GtkWidget *prices1;
  GtkWidget *ids1;
  GtkWidget *image94;
  GtkWidget *ecyes1;
  GSList *ecyes1_group = NULL;
  GtkWidget *car1;
  GtkWidget *camion1;
  GtkWidget *confirmas;
  GtkWidget *alignment2;
  GtkWidget *hbox63;
  GtkWidget *image95;
  GtkWidget *label328;
  GtkWidget *label327;
  GtkWidget *label178;
  GtkWidget *label180;
  GtkWidget *label181;
  GtkWidget *label323;
  GtkWidget *label326;
  GtkWidget *ecno1;
  GtkWidget *image106;
  GtkWidget *label335;
  GtkWidget *image107;
  GtkWidget *_;
  GtkWidget *fixed40;
  GtkWidget *names2;
  GtkWidget *prices2;
  GtkObject *duration2_adj;
  GtkWidget *duration2;
  GtkWidget *idms;
  GtkWidget *car2;
  GtkWidget *camion2;
  GtkWidget *hseparator1;
  GtkWidget *label182;
  GtkWidget *refreshms;
  GtkWidget *alignment3;
  GtkWidget *hbox64;
  GtkWidget *image96;
  GtkWidget *label329;
  GtkWidget *label184;
  GtkWidget *label185;
  GtkWidget *label186;
  GtkWidget *label324;
  GtkWidget *label325;
  GtkWidget *confirmms;
  GtkWidget *alignment4;
  GtkWidget *hbox65;
  GtkWidget *image97;
  GtkWidget *label330;
  GtkWidget *image100;
  GtkWidget *ecyes2;
  GSList *ecyes2_group = NULL;
  GtkWidget *ecno2;
  GtkWidget *image108;
  GtkWidget *image109;
  GtkWidget *label336;
  GtkWidget *label172;
  GtkWidget *fixed37;
  GtkWidget *idds;
  GtkWidget *label187;
  GtkWidget *refreshds;
  GtkWidget *alignment5;
  GtkWidget *hbox66;
  GtkWidget *image98;
  GtkWidget *label331;
  GtkWidget *deleteds;
  GtkWidget *alignment6;
  GtkWidget *hbox67;
  GtkWidget *image99;
  GtkWidget *label332;
  GtkWidget *image101;
  GtkWidget *label173;
  GtkWidget *fixed38;
  GtkWidget *treeview9;
  GtkWidget *despaly;
  GtkWidget *alignment7;
  GtkWidget *hbox68;
  GtkWidget *image102;
  GtkWidget *label333;
  GtkWidget *image105;
  GtkWidget *label174;
  GtkWidget *fixed39;
  GtkWidget *effect_id;
  GtkWidget *entry_res;
  GtkWidget *label188;
  GtkWidget *label189;
  GtkWidget *effectres;
  GtkWidget *alignment8;
  GtkWidget *hbox69;
  GtkWidget *image103;
  GtkWidget *label334;
  GtkWidget *image104;
  GtkWidget *image111;
  GtkWidget *image110;
  GtkWidget *image112;
  GtkWidget *label337;
  GtkWidget *label175;
  GtkWidget *label106;

  Admin_Space_V2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Admin_Space_V2), _("Admin Space"));
  gtk_window_set_resizable (GTK_WINDOW (Admin_Space_V2), FALSE);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (Admin_Space_V2), notebook1);

  notebook4 = gtk_notebook_new ();
  gtk_widget_show (notebook4);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook4);

  hbox60 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox60);
  gtk_container_add (GTK_CONTAINER (notebook4), hbox60);

  fixed35 = gtk_fixed_new ();
  gtk_widget_show (fixed35);
  gtk_box_pack_start (GTK_BOX (hbox60), fixed35, TRUE, TRUE, 0);
  gtk_widget_set_size_request (fixed35, 31, 328);

  names1 = gtk_entry_new ();
  gtk_widget_show (names1);
  gtk_fixed_put (GTK_FIXED (fixed35), names1, 224, 88);
  gtk_widget_set_size_request (names1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (names1), 8226);

  durations1_adj = gtk_adjustment_new (10, 10, 120, 1, 10, 10);
  durations1 = gtk_spin_button_new (GTK_ADJUSTMENT (durations1_adj), 1, 0);
  gtk_widget_show (durations1);
  gtk_fixed_put (GTK_FIXED (fixed35), durations1, 232, 128);
  gtk_widget_set_size_request (durations1, 60, 27);

  prices1 = gtk_entry_new ();
  gtk_widget_show (prices1);
  gtk_fixed_put (GTK_FIXED (fixed35), prices1, 224, 176);
  gtk_widget_set_size_request (prices1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prices1), 8226);

  ids1 = gtk_entry_new ();
  gtk_widget_show (ids1);
  gtk_fixed_put (GTK_FIXED (fixed35), ids1, 224, 56);
  gtk_widget_set_size_request (ids1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ids1), 8226);

  image94 = create_pixmap (Admin_Space_V2, "logo.png");
  gtk_widget_show (image94);
  gtk_fixed_put (GTK_FIXED (fixed35), image94, 480, 40);
  gtk_widget_set_size_request (image94, 133, 120);

  ecyes1 = gtk_radio_button_new_with_mnemonic (NULL, _("yes"));
  gtk_widget_show (ecyes1);
  gtk_fixed_put (GTK_FIXED (fixed35), ecyes1, 224, 224);
  gtk_widget_set_size_request (ecyes1, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ecyes1), ecyes1_group);
  ecyes1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ecyes1));

  car1 = gtk_check_button_new_with_mnemonic (_("car"));
  gtk_widget_show (car1);
  gtk_fixed_put (GTK_FIXED (fixed35), car1, 224, 296);
  gtk_widget_set_size_request (car1, 126, 24);

  camion1 = gtk_check_button_new_with_mnemonic (_("camion"));
  gtk_widget_show (camion1);
  gtk_fixed_put (GTK_FIXED (fixed35), camion1, 224, 272);
  gtk_widget_set_size_request (camion1, 126, 24);

  confirmas = gtk_button_new ();
  gtk_widget_show (confirmas);
  gtk_fixed_put (GTK_FIXED (fixed35), confirmas, 277, 352);
  gtk_widget_set_size_request (confirmas, 90, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (confirmas), alignment2);

  hbox63 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox63);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox63);

  image95 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image95);
  gtk_box_pack_start (GTK_BOX (hbox63), image95, FALSE, FALSE, 0);

  label328 = gtk_label_new_with_mnemonic (_("<span\nforeground=\"green\"><b>confirm</b></span>"));
  gtk_widget_show (label328);
  gtk_box_pack_start (GTK_BOX (hbox63), label328, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label328), TRUE);

  label327 = gtk_label_new (_("<span\nforeground=\"black\"><b>service id:</b></span>"));
  gtk_widget_show (label327);
  gtk_fixed_put (GTK_FIXED (fixed35), label327, 96, 56);
  gtk_widget_set_size_request (label327, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (label327), TRUE);

  label178 = gtk_label_new (_("<span\nforeground=\"black\"><b>Service Name:</b></span>"));
  gtk_widget_show (label178);
  gtk_fixed_put (GTK_FIXED (fixed35), label178, 92, 88);
  gtk_widget_set_size_request (label178, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (label178), TRUE);

  label180 = gtk_label_new (_("<span\nforeground=\"black\"><b>Duration (min):</b></span>"));
  gtk_widget_show (label180);
  gtk_fixed_put (GTK_FIXED (fixed35), label180, 96, 136);
  gtk_widget_set_size_request (label180, 120, 24);
  gtk_label_set_use_markup (GTK_LABEL (label180), TRUE);

  label181 = gtk_label_new (_("<span\nforeground=\"black\"><b>Price: </b></span>"));
  gtk_widget_show (label181);
  gtk_fixed_put (GTK_FIXED (fixed35), label181, 98, 176);
  gtk_widget_set_size_request (label181, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label181), TRUE);

  label323 = gtk_label_new (_("<span\nforeground=\"black\"><b>electrique car:</b></span>"));
  gtk_widget_show (label323);
  gtk_fixed_put (GTK_FIXED (fixed35), label323, 96, 224);
  gtk_widget_set_size_request (label323, 120, 24);
  gtk_label_set_use_markup (GTK_LABEL (label323), TRUE);

  label326 = gtk_label_new (_("<span\nforeground=\"black\"><b>service for:</b></span>"));
  gtk_widget_show (label326);
  gtk_fixed_put (GTK_FIXED (fixed35), label326, 96, 264);
  gtk_widget_set_size_request (label326, 96, 24);
  gtk_label_set_use_markup (GTK_LABEL (label326), TRUE);

  ecno1 = gtk_radio_button_new_with_mnemonic (NULL, _("no"));
  gtk_widget_show (ecno1);
  gtk_fixed_put (GTK_FIXED (fixed35), ecno1, 320, 120);
  gtk_widget_set_size_request (ecno1, 245, 232);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ecno1), ecyes1_group);
  ecyes1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ecno1));

  image106 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image106);
  gtk_fixed_put (GTK_FIXED (fixed35), image106, 392, 59);
  gtk_widget_set_size_request (image106, 21, 21);

  label335 = gtk_label_new (_("<span\nforeground=\"red\"><b>champ obligatoire ! </b></span>"));
  gtk_widget_show (label335);
  gtk_fixed_put (GTK_FIXED (fixed35), label335, 105, 329);
  gtk_widget_set_size_request (label335, 143, 17);
  gtk_label_set_use_markup (GTK_LABEL (label335), TRUE);

  image107 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image107);
  gtk_fixed_put (GTK_FIXED (fixed35), image107, 82, 328);
  gtk_widget_set_size_request (image107, 21, 21);

  _ = gtk_label_new (_("<span\nforeground=\"blue\"><b>Add</b></span>"));
  gtk_widget_show (_);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 0), _);
  gtk_label_set_use_markup (GTK_LABEL (_), TRUE);

  fixed40 = gtk_fixed_new ();
  gtk_widget_show (fixed40);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed40);

  names2 = gtk_entry_new ();
  gtk_widget_show (names2);
  gtk_fixed_put (GTK_FIXED (fixed40), names2, 184, 128);
  gtk_widget_set_size_request (names2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (names2), 8226);

  prices2 = gtk_entry_new ();
  gtk_widget_show (prices2);
  gtk_fixed_put (GTK_FIXED (fixed40), prices2, 184, 192);
  gtk_widget_set_size_request (prices2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prices2), 8226);

  duration2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  duration2 = gtk_spin_button_new (GTK_ADJUSTMENT (duration2_adj), 1, 0);
  gtk_widget_show (duration2);
  gtk_fixed_put (GTK_FIXED (fixed40), duration2, 184, 160);
  gtk_widget_set_size_request (duration2, 60, 27);

  idms = gtk_combo_box_new_text ();
  gtk_widget_show (idms);
  gtk_fixed_put (GTK_FIXED (fixed40), idms, 187, 30);
  gtk_widget_set_size_request (idms, 162, 31);

  car2 = gtk_check_button_new_with_mnemonic (_("car"));
  gtk_widget_show (car2);
  gtk_fixed_put (GTK_FIXED (fixed40), car2, 184, 304);
  gtk_widget_set_size_request (car2, 126, 24);

  camion2 = gtk_check_button_new_with_mnemonic (_("camion"));
  gtk_widget_show (camion2);
  gtk_fixed_put (GTK_FIXED (fixed40), camion2, 184, 280);
  gtk_widget_set_size_request (camion2, 126, 24);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed40), hseparator1, 0, 56);
  gtk_widget_set_size_request (hseparator1, 688, 16);

  label182 = gtk_label_new (_("<span\nforeground=\"black\"><b>Old Service ID:</b></span>"));
  gtk_widget_show (label182);
  gtk_fixed_put (GTK_FIXED (fixed40), label182, 64, 32);
  gtk_widget_set_size_request (label182, 120, 24);
  gtk_label_set_use_markup (GTK_LABEL (label182), TRUE);

  refreshms = gtk_button_new ();
  gtk_widget_show (refreshms);
  gtk_fixed_put (GTK_FIXED (fixed40), refreshms, 352, 32);
  gtk_widget_set_size_request (refreshms, 82, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (refreshms), alignment3);

  hbox64 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox64);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox64);

  image96 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image96);
  gtk_box_pack_start (GTK_BOX (hbox64), image96, FALSE, FALSE, 0);

  label329 = gtk_label_new_with_mnemonic (_("<span\nforeground=\"blue\"><b>refresh</b></span>"));
  gtk_widget_show (label329);
  gtk_box_pack_start (GTK_BOX (hbox64), label329, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label329), TRUE);

  label184 = gtk_label_new (_("<span\nforeground=\"black\"><b>New service Name: </b></span>"));
  gtk_widget_show (label184);
  gtk_fixed_put (GTK_FIXED (fixed40), label184, 32, 128);
  gtk_widget_set_size_request (label184, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (label184), TRUE);

  label185 = gtk_label_new (_("<span\nforeground=\"black\"><b>New service duration:</b></span>"));
  gtk_widget_show (label185);
  gtk_fixed_put (GTK_FIXED (fixed40), label185, 16, 168);
  gtk_widget_set_size_request (label185, 160, 16);
  gtk_label_set_use_markup (GTK_LABEL (label185), TRUE);

  label186 = gtk_label_new (_("<span\nforeground=\"black\"><b>New service price:</b></span>"));
  gtk_widget_show (label186);
  gtk_fixed_put (GTK_FIXED (fixed40), label186, 24, 200);
  gtk_widget_set_size_request (label186, 168, 16);
  gtk_label_set_use_markup (GTK_LABEL (label186), TRUE);

  label324 = gtk_label_new (_("<span\nforeground=\"black\"><b>electrique car :</b></span>"));
  gtk_widget_show (label324);
  gtk_fixed_put (GTK_FIXED (fixed40), label324, 56, 240);
  gtk_widget_set_size_request (label324, 129, 16);
  gtk_label_set_use_markup (GTK_LABEL (label324), TRUE);

  label325 = gtk_label_new (_("<span\nforeground=\"black\"><b>service for:</b></span>"));
  gtk_widget_show (label325);
  gtk_fixed_put (GTK_FIXED (fixed40), label325, 64, 280);
  gtk_widget_set_size_request (label325, 105, 24);
  gtk_label_set_use_markup (GTK_LABEL (label325), TRUE);

  confirmms = gtk_button_new ();
  gtk_widget_show (confirmms);
  gtk_fixed_put (GTK_FIXED (fixed40), confirmms, 232, 376);
  gtk_widget_set_size_request (confirmms, 81, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (confirmms), alignment4);

  hbox65 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox65);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox65);

  image97 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image97);
  gtk_box_pack_start (GTK_BOX (hbox65), image97, FALSE, FALSE, 0);

  label330 = gtk_label_new_with_mnemonic (_("<span\nforeground=\"green\"><b>confirm</b></span>"));
  gtk_widget_show (label330);
  gtk_box_pack_start (GTK_BOX (hbox65), label330, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label330), TRUE);

  image100 = create_pixmap (Admin_Space_V2, "logo.png");
  gtk_widget_show (image100);
  gtk_fixed_put (GTK_FIXED (fixed40), image100, 512, 96);
  gtk_widget_set_size_request (image100, 112, 101);

  ecyes2 = gtk_radio_button_new_with_mnemonic (NULL, _("yes"));
  gtk_widget_show (ecyes2);
  gtk_fixed_put (GTK_FIXED (fixed40), ecyes2, 184, 240);
  gtk_widget_set_size_request (ecyes2, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ecyes2), ecyes2_group);
  ecyes2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ecyes2));

  ecno2 = gtk_radio_button_new_with_mnemonic (NULL, _("no"));
  gtk_widget_show (ecno2);
  gtk_fixed_put (GTK_FIXED (fixed40), ecno2, 304, 240);
  gtk_widget_set_size_request (ecno2, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ecno2), ecyes2_group);
  ecyes2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ecno2));

  image108 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image108);
  gtk_fixed_put (GTK_FIXED (fixed40), image108, 352, 131);
  gtk_widget_set_size_request (image108, 21, 21);

  image109 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image109);
  gtk_fixed_put (GTK_FIXED (fixed40), image109, 16, 336);
  gtk_widget_set_size_request (image109, 21, 21);

  label336 = gtk_label_new (_("<span\nforeground=\"red\"><b>champ obligatoire ! </b></span>"));
  gtk_widget_show (label336);
  gtk_fixed_put (GTK_FIXED (fixed40), label336, 38, 337);
  gtk_widget_set_size_request (label336, 150, 17);
  gtk_label_set_use_markup (GTK_LABEL (label336), TRUE);

  label172 = gtk_label_new (_("<span\nforeground=\"blue\"><b>Modifie</b></span>"));
  gtk_widget_show (label172);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 1), label172);
  gtk_label_set_use_markup (GTK_LABEL (label172), TRUE);

  fixed37 = gtk_fixed_new ();
  gtk_widget_show (fixed37);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed37);

  idds = gtk_combo_box_new_text ();
  gtk_widget_show (idds);
  gtk_fixed_put (GTK_FIXED (fixed37), idds, 167, 23);
  gtk_widget_set_size_request (idds, 162, 31);

  label187 = gtk_label_new (_("<span\nforeground=\"black\"><b>Service ID: </b></span>"));
  gtk_widget_show (label187);
  gtk_fixed_put (GTK_FIXED (fixed37), label187, 64, 32);
  gtk_widget_set_size_request (label187, 96, 16);
  gtk_label_set_use_markup (GTK_LABEL (label187), TRUE);

  refreshds = gtk_button_new ();
  gtk_widget_show (refreshds);
  gtk_fixed_put (GTK_FIXED (fixed37), refreshds, 336, 24);
  gtk_widget_set_size_request (refreshds, 82, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (refreshds), alignment5);

  hbox66 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox66);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox66);

  image98 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image98);
  gtk_box_pack_start (GTK_BOX (hbox66), image98, FALSE, FALSE, 0);

  label331 = gtk_label_new_with_mnemonic (_("<span\nforeground=\"blue\"><b>refresh</b></span>"));
  gtk_widget_show (label331);
  gtk_box_pack_start (GTK_BOX (hbox66), label331, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label331), TRUE);

  deleteds = gtk_button_new ();
  gtk_widget_show (deleteds);
  gtk_fixed_put (GTK_FIXED (fixed37), deleteds, 208, 128);
  gtk_widget_set_size_request (deleteds, 82, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (deleteds), alignment6);

  hbox67 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox67);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox67);

  image99 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image99);
  gtk_box_pack_start (GTK_BOX (hbox67), image99, FALSE, FALSE, 0);

  label332 = gtk_label_new_with_mnemonic (_("<span\nforeground=\"red\"><b>Delete</b></span>"));
  gtk_widget_show (label332);
  gtk_box_pack_start (GTK_BOX (hbox67), label332, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label332), TRUE);

  image101 = create_pixmap (Admin_Space_V2, "logo.png");
  gtk_widget_show (image101);
  gtk_fixed_put (GTK_FIXED (fixed37), image101, 448, 32);
  gtk_widget_set_size_request (image101, 207, 144);

  label173 = gtk_label_new (_("<span\nforeground=\"blue\"><b>Delete</b></span>"));
  gtk_widget_show (label173);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 2), label173);
  gtk_label_set_use_markup (GTK_LABEL (label173), TRUE);

  fixed38 = gtk_fixed_new ();
  gtk_widget_show (fixed38);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed38);

  treeview9 = gtk_tree_view_new ();
  gtk_widget_show (treeview9);
  gtk_fixed_put (GTK_FIXED (fixed38), treeview9, 40, 72);
  gtk_widget_set_size_request (treeview9, 472, 200);

  despaly = gtk_button_new ();
  gtk_widget_show (despaly);
  gtk_fixed_put (GTK_FIXED (fixed38), despaly, 280, 352);
  gtk_widget_set_size_request (despaly, 82, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (despaly), alignment7);

  hbox68 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox68);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox68);

  image102 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image102);
  gtk_box_pack_start (GTK_BOX (hbox68), image102, FALSE, FALSE, 0);

  label333 = gtk_label_new_with_mnemonic (_("<span\nforeground=\"green\"><b>show</b></span>"));
  gtk_widget_show (label333);
  gtk_box_pack_start (GTK_BOX (hbox68), label333, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label333), TRUE);

  image105 = create_pixmap (Admin_Space_V2, "logo.png");
  gtk_widget_show (image105);
  gtk_fixed_put (GTK_FIXED (fixed38), image105, 536, 40);
  gtk_widget_set_size_request (image105, 120, 120);

  label174 = gtk_label_new (_("<span\nforeground=\"blue\"><b>Desplay</b></span>"));
  gtk_widget_show (label174);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 3), label174);
  gtk_label_set_use_markup (GTK_LABEL (label174), TRUE);

  fixed39 = gtk_fixed_new ();
  gtk_widget_show (fixed39);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed39);

  effect_id = gtk_entry_new ();
  gtk_widget_show (effect_id);
  gtk_fixed_put (GTK_FIXED (fixed39), effect_id, 240, 112);
  gtk_widget_set_size_request (effect_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (effect_id), 8226);

  entry_res = gtk_entry_new ();
  gtk_widget_show (entry_res);
  gtk_fixed_put (GTK_FIXED (fixed39), entry_res, 240, 160);
  gtk_widget_set_size_request (entry_res, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_res), 8226);

  label188 = gtk_label_new (_("<span\nforeground=\"black\"><b>Service ID:</b></span>"));
  gtk_widget_show (label188);
  gtk_fixed_put (GTK_FIXED (fixed39), label188, 104, 120);
  gtk_widget_set_size_request (label188, 104, 16);
  gtk_label_set_use_markup (GTK_LABEL (label188), TRUE);

  label189 = gtk_label_new (_("<span\nforeground=\"black\"><b>Resarvation ID:</b></span>\n"));
  gtk_widget_show (label189);
  gtk_fixed_put (GTK_FIXED (fixed39), label189, 112, 168);
  gtk_widget_set_size_request (label189, 112, 16);
  gtk_label_set_use_markup (GTK_LABEL (label189), TRUE);

  effectres = gtk_button_new ();
  gtk_widget_show (effectres);
  gtk_fixed_put (GTK_FIXED (fixed39), effectres, 270, 248);
  gtk_widget_set_size_request (effectres, 83, 35);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (effectres), alignment8);

  hbox69 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox69);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox69);

  image103 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image103);
  gtk_box_pack_start (GTK_BOX (hbox69), image103, FALSE, FALSE, 0);

  label334 = gtk_label_new_with_mnemonic (_("<span\nforeground=\"green\"><b>Affect</b></span>"));
  gtk_widget_show (label334);
  gtk_box_pack_start (GTK_BOX (hbox69), label334, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label334), TRUE);

  image104 = create_pixmap (Admin_Space_V2, "logo.png");
  gtk_widget_show (image104);
  gtk_fixed_put (GTK_FIXED (fixed39), image104, 488, 40);
  gtk_widget_set_size_request (image104, 128, 120);

  image111 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image111);
  gtk_fixed_put (GTK_FIXED (fixed39), image111, 406, 160);
  gtk_widget_set_size_request (image111, 18, 29);

  image110 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image110);
  gtk_fixed_put (GTK_FIXED (fixed39), image110, 408, 114);
  gtk_widget_set_size_request (image110, 21, 21);

  image112 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image112);
  gtk_fixed_put (GTK_FIXED (fixed39), image112, 23, 212);
  gtk_widget_set_size_request (image112, 21, 21);

  label337 = gtk_label_new (_("<span\nforeground=\"red\"><b>champ obligatoire ! </b></span>"));
  gtk_widget_show (label337);
  gtk_fixed_put (GTK_FIXED (fixed39), label337, 42, 212);
  gtk_widget_set_size_request (label337, 151, 20);
  gtk_label_set_use_markup (GTK_LABEL (label337), TRUE);

  label175 = gtk_label_new (_("<span\nforeground=\"blue\"><b>Affect</b></span>"));
  gtk_widget_show (label175);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 4), label175);
  gtk_label_set_use_markup (GTK_LABEL (label175), TRUE);

  label106 = gtk_label_new (_(" Services "));
  gtk_widget_show (label106);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label106);

  g_signal_connect ((gpointer) ecyes1, "toggled",
                    G_CALLBACK (on_ecyes1_toggled),
                    NULL);
  g_signal_connect ((gpointer) car1, "toggled",
                    G_CALLBACK (on_car1_toggled),
                    NULL);
  g_signal_connect ((gpointer) camion1, "toggled",
                    G_CALLBACK (on_camion1_toggled),
                    NULL);
  g_signal_connect ((gpointer) confirmas, "clicked",
                    G_CALLBACK (on_confirmas_clicked),
                    NULL);
  g_signal_connect ((gpointer) ecno1, "toggled",
                    G_CALLBACK (on_ecno1_toggled),
                    NULL);
  g_signal_connect ((gpointer) car2, "toggled",
                    G_CALLBACK (on_car2_toggled),
                    NULL);
  g_signal_connect ((gpointer) camion2, "toggled",
                    G_CALLBACK (on_camion2_toggled),
                    NULL);
  g_signal_connect ((gpointer) refreshms, "clicked",
                    G_CALLBACK (on_refreshms_clicked),
                    NULL);
  g_signal_connect ((gpointer) confirmms, "clicked",
                    G_CALLBACK (on_confirmms_clicked),
                    NULL);
  g_signal_connect ((gpointer) ecyes2, "toggled",
                    G_CALLBACK (on_ecyes2_toggled),
                    NULL);
  g_signal_connect ((gpointer) ecno2, "toggled",
                    G_CALLBACK (on_ecno2_toggled),
                    NULL);
  g_signal_connect ((gpointer) refreshds, "clicked",
                    G_CALLBACK (on_refreshds_clicked),
                    NULL);
  g_signal_connect ((gpointer) deleteds, "clicked",
                    G_CALLBACK (on_deleteds_clicked),
                    NULL);
  g_signal_connect ((gpointer) despaly, "clicked",
                    G_CALLBACK (on_despaly_clicked),
                    NULL);
  g_signal_connect ((gpointer) effectres, "clicked",
                    G_CALLBACK (on_effectres_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Admin_Space_V2, Admin_Space_V2, "Admin_Space_V2");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, notebook4, "notebook4");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, hbox60, "hbox60");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, fixed35, "fixed35");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, names1, "names1");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, durations1, "durations1");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, prices1, "prices1");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, ids1, "ids1");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image94, "image94");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, ecyes1, "ecyes1");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, car1, "car1");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, camion1, "camion1");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, confirmas, "confirmas");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, hbox63, "hbox63");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image95, "image95");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label328, "label328");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label327, "label327");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label178, "label178");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label180, "label180");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label181, "label181");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label323, "label323");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label326, "label326");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, ecno1, "ecno1");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image106, "image106");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label335, "label335");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image107, "image107");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, _, "_");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, fixed40, "fixed40");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, names2, "names2");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, prices2, "prices2");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, duration2, "duration2");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, idms, "idms");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, car2, "car2");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, camion2, "camion2");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label182, "label182");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, refreshms, "refreshms");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, hbox64, "hbox64");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image96, "image96");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label329, "label329");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label184, "label184");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label185, "label185");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label186, "label186");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label324, "label324");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label325, "label325");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, confirmms, "confirmms");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, hbox65, "hbox65");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image97, "image97");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label330, "label330");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image100, "image100");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, ecyes2, "ecyes2");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, ecno2, "ecno2");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image108, "image108");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image109, "image109");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label336, "label336");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label172, "label172");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, fixed37, "fixed37");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, idds, "idds");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label187, "label187");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, refreshds, "refreshds");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, hbox66, "hbox66");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image98, "image98");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label331, "label331");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, deleteds, "deleteds");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, hbox67, "hbox67");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image99, "image99");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label332, "label332");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image101, "image101");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label173, "label173");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, fixed38, "fixed38");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, treeview9, "treeview9");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, despaly, "despaly");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, hbox68, "hbox68");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image102, "image102");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label333, "label333");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image105, "image105");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label174, "label174");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, fixed39, "fixed39");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, effect_id, "effect_id");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, entry_res, "entry_res");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label188, "label188");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label189, "label189");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, effectres, "effectres");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, hbox69, "hbox69");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image103, "image103");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label334, "label334");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image104, "image104");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image111, "image111");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image110, "image110");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, image112, "image112");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label337, "label337");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label175, "label175");
  GLADE_HOOKUP_OBJECT (Admin_Space_V2, label106, "label106");

  return Admin_Space_V2;
}

